# Generated by Django 4.2.18 on 2025-02-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
