# Generated by Django 4.2.18 on 2025-03-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
