# Generated by Django 4.2.18 on 2025-02-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
    ]
