# Generated by Django 4.2.17 on 2025-01-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_questionreaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
