# Generated by Django 4.2.17 on 2025-01-10 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0015_rename_approved_reply_is_approved_alter_reply_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True,
                related_name="disliked_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_questions", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
