# Generated by Django 4.2.17 on 2025-01-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_question_dislikes_question_likes_alter_question_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="question",
            name="likes",
        ),
    ]
