# Generated by Django 4.2.17 on 2025-01-10 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0017_remove_question_dislikes_remove_question_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="dislikes_count",
            field=models.ManyToManyField(
                blank=True,
                related_name="disliked_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="likes_count",
            field=models.ManyToManyField(
                blank=True, related_name="liked_questions", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
