# Generated by Django 4.2.17 on 2025-01-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_question_dislikes_count_question_likes_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name_plural": "Question"},
        ),
    ]
