# Generated by Django 4.2.17 on 2025-01-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_question_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("color", models.CharField(default="#000000", max_length=7)),
            ],
        ),
        migrations.AlterModelOptions(
            name="question",
            options={},
        ),
        migrations.AddField(
            model_name="question",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="questions", to="home.label"
            ),
        ),
    ]
