# Generated by Django 4.2.18 on 2025-01-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_label_alter_question_options_question_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
