# Generated by Django 4.2.18 on 2025-01-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_userprofile_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
